ALTER TABLE polls 
  ALTER COLUMN option1 SET DEFAULT NULL,
  ALTER COLUMN option2 SET DEFAULT NULL,
  ALTER COLUMN option3 SET DEFAULT NULL,
  ALTER COLUMN option4 SET DEFAULT NULL,
  ALTER COLUMN option5 SET DEFAULT NULL;

ALTER TABLE polls 
  ALTER COLUMN option1 TYPE VARCHAR(50),
  ALTER COLUMN option2 TYPE VARCHAR(50),
  ALTER COLUMN option3 TYPE VARCHAR(50),
  ALTER COLUMN option4 TYPE VARCHAR(50),
  ALTER COLUMN option5 TYPE VARCHAR(50);